language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls
  - pip install pycodestyle
  - export USER_CREATE_SETTINGS_FILE=$(pwd)/config/user-create.ini

script:
  - pycodestyle --max-line-length=120 .
  - nosetests --with-coverage --cover-package=./ --exe

after_success:
  coveralls
