---
# ------------------------
# Deploy the general stuff
# ------------------------
- hosts: user-create
  become: yes
  # strategy: debug

  vars_files:
    - vars/data.yml


  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  tasks:
    # General tasks
    - name: install pip
      apt: name=python-pip state=present update_cache=yes

    - name: install virtualenv
      apt: name=python-virtualenv state=present update_cache=yes

    - name: disable net.ipv6.conf.all.disable_ipv6
      sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

    - name: disable net.ipv6.conf.default.disable_ipv6
      sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present
 
    - name: disable net.ipv6.conf.lo.disable_ipv6
      sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

    # Setting up the environment
    - name: distribute your cloud credentials into a file
      template: src=templates/.openrc.j2 dest=/home/fla/.openrc mode=0664

    # Create logs directory (initially empty)
    #- name: Create the logs directory.
    #  shell: mkdir fiware.d
    #  args:
    #    chdir: /etc

    # Problems:
    # pip is not updated

    - name: distribute the user-create.ini file
      template: src=templates/user-create.ini.j2 dest=/etc/fiware.d/user-create.ini mode=0664

    # Clone repository
    - git:
        repo: https://github.com/flopezag/fiware-user-creation.git
        dest: /home/fla/fiware-user-creation

    # Change to develop branch
    - name: Change the working directory to fiware-user-creation/ before changing the branch to develop.
      shell: git checkout develop
      args:
        chdir: fiware-user-creation/

    # Configure files
    - name: Give execution permission to the config.sh file
      shell: sudo chmod 764 ./config.sh
      args:
        chdir: fiware-user-creation/deploy/

    # Configure files
    - name: Run the config.sh script and configure the environment
      shell: sudo ./config.sh >> config.log 2>error.out
      args:
        chdir: fiware-user-creation/deploy/

    # Configure logrotate
    - name: Copy logrotate configuration file
      shell: sudo cp ./fiware-user-creation/config/user-create.logrotate /etc/logrotate.d/user-create

    # Create logs directory (initially empty)
    - name: Create the logs directory.
      shell: mkdir logs
      args:
        chdir: fiware-user-creation/
